import { Colors } from "@/application/enums/app/common/Colors";
import { ProjectStatus } from "@/application/enums/app/projects/ProjectStatus";
import { ProjectView } from "@/application/enums/app/projects/ProjectView";
import { UserDto } from "../../master/users/UserDto";
import { AppWorkspaceEntityDto } from "../AppWorkspaceEntityDto";
import { CfdiDto } from "../cfdis/CfdiDto";
import { TicketDto } from "../transactions/TicketDto";
import { TransactionDto } from "../transactions/TransactionDto";
import { TeamDto } from "./TeamDto";
import { ProjectCustomField } from "./ProjectCustomField";
import { ProjectMultimediaDto } from "./ProjectMultimediaDto";
import { ProjectSectionDto } from "./ProjectSectionDto";
import { ProjectMemberDto } from "./ProjectMemberDto";
import {CustomerDto} from "@/application/dtos/app/contacts/CustomerDto";
import {SupplierDto} from "@/application/dtos/app/contacts/SupplierDto";
import {WorkspaceDto} from "@/application/dtos/app/workspaces/WorkspaceDto";
import {SummaryCountTotalResponse} from "@/application/contracts/app/summaries/SummaryCountTotalResponse";

export interface ProjectDto extends AppWorkspaceEntityDto {
  teamId: string | null;
  team: TeamDto;
  name: string;
  description: string;
  startDate?: string | null;
  endDate?: string | null;
  default: boolean;
  color: Colors;
  public: boolean;
  slug: string;
  customerId: string | null;
  customer: CustomerDto;
  supplierId: string | null;
  supplier: SupplierDto;
  managerId: string | null;
  manager: UserDto;
  status: ProjectStatus;
  completionDate: string | null;
  view: ProjectView;
  groupedByFieldId: string;
  groupedByField: ProjectCustomField;
  filterBy: string[];
  orderBy: string[];
  budget: number;
  multimedia: ProjectMultimediaDto[];
  sections: ProjectSectionDto[];
  fields: ProjectCustomField[];
  tickets: TicketDto[];
  transactions: TransactionDto[];
  cfdis: CfdiDto[];
  members: ProjectMemberDto[];
  summary?: SummaryCountTotalResponse;
}
